---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAe/CTL+AsP7iplba9r2A71vgVOmAXI7Rylcyh7kF+nD86cjcZ5TGJI1LogC4XeblCgXLMGL1GGAoCrU7dfnmPWt8GVdlaz4JK/LmMOtXFeOFAyQ1G0P0c4WXgUjtjpbiUppGDIqK7a1L5LxLkqyiMZgXsaeiOismNtRPMFNxsimrkr/YhXhg+hqf+NJ80AxBSOHCUMsra9WPY6u7R2vz/MkKqE40dxYwhaT/x9UNIawbAC3hJyXFSkOPqwzEDOKnIgzpX+2vSlxk9tOTDCBuLil99JuW92ITH/M5BaktbY+mBBg26ArvxfBoyuEoc6U5Q4iGWrLXR6BJbLwRMU0LgsHQ2W7WOp7iw8W6vQMZer3nE+i8SScesuQJVeZK54MiWecT0uEDcdXz3d3MHMNt3NDacqv5sewtARkIl4EQLr5AxDUm6Frz+0fy2VCAk2aernvqiBNewUvNcrD+iuK5Jcvod6o9ddiM/QhjcnzKJyADKUCL0BmVqUGAAjjJ/ZtWgtZ59UFjBAdUmL7wTikOMUCFViVva6N32HfxQ8hWrMQrnptHby/eGXBPKWly/yXbKDYnQOyQpLjUNjOyb3Aq4uT0087s9ynlkG6Oi5p/tSTkdzZSq3Lp5OM84QshlYLriFiNpobcRpSBXLqK+1MqkL4XWSkmH7R1g3yAT6uAHlKybTudIA2tUQeByIyAi8jAHNDB115+gpk+4Fu7b516QcxB9ar9MEAYoZLqMJgM1c0Q==
    admin-user: AgA1wNt+F1pcpFFNX40rnxJMt0Q625TBjaDs6SWFAuZvTKznZvt9NLy6Pjtgo6JD6R3CeaZxxU4Wwq+ZyANRDzQOJfzolaA46ZkxONlSwm03BI44EQORAlP2O9Kd0M7bQ5CIl8OSbee5V9O0fHZfDq4d/RvCXL7PCHy0CpN+2Wi2kvLgmLlIQyq8lYGnaq1Fvd8BbDg29dpFh2bEybe5kCpAYBKOsb84HHEcMQn3BCiwxpNrWqElor53OwlGbWRTGa7gvxUq2mtuxYLJZVJ1EqqSAwvZQ/6l6wxhT7yVaz0Wfnxzl67nq5V6bfZ4UZyK6Lwd0BhfUXRQYSeV/7+GL3igf4d5wACbOkU6v6Hhw0J+FDrIQL0ZwOrKsBkQ78Taopar8eUYhQ3A6tw+Q1m6BSV+MmuhXO1Dvt02Z6DkBt6+tQ0Wy5luCVRTwKoSJUt3vslPil4GwvIgT0LMyuy+YAvBfvmYdvjJA1qrvAx2OTbDh7OLR2bXdxLKW8TG2NCptt7c8QnoMYAf2mJ8vTDXvU+Euc9NH4FaVMRgiVECU6xl7G8zHSunoVQcKrGLh7ZHXO6AJidqlTrpPY2ZdvJaDdap9dITI0gulplfL88WaOf83seM13a/q8AZat4tr9zfEVQCMqMATcS+K0etaiabJhtZw5INiZzFWTXGN/XwWTuspya85F2ePywK54z/JsCcSSJVcBW3/Q==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
