apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shop-rabbitmq
  namespace: shop
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: rabbitmq }
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [{ podSelector: { matchLabels: { app.kubernetes.io/part-of: shop } } }]
      ports: [{ port: 5672 }]         # AMQP
    - from: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: ingress-nginx } } }]
      ports: [{ port: 15672 }]        # management UI (rabbitmq.shop.localtest.me)
    - from: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: monitoring } } }]
      ports: [{ port: 9419 }]         # rabbitmq_prometheus (bitnami: metrics на 9419)
