apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # порядок в app-of-apps: меньше — раньше
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # multi-source: [0] чарт из репозитория чартов (версия = targetRevision), [1] наш git как источник values ($values)
  sources:
    - repoURL: https://charts.fairwinds.com/stable
      chart: vpa
      targetRevision: 5.0.0
      helm:
        releaseName: vpa
        valueFiles:
          - $values/infra/values/vpa.yaml
    - repoURL: https://github.com/CHoNChmonich/argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
