apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # порядок в app-of-apps: меньше — раньше
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  # multi-source: [0] чарт из репозитория чартов (версия = targetRevision), [1] наш git как источник values ($values)
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 7.3.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/infra/values/loki.yaml
    - repoURL: https://github.com/CHoNChmonich/argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
