# Bitnami из OCI-registry (Secret repo-bitnamicharts). Образы — bitnamilegacy, см. values.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # порядок в app-of-apps: меньше — раньше
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # multi-source: [0] чарт из репозитория чартов (версия = targetRevision), [1] наш git как источник values ($values)
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: redis
      targetRevision: 20.13.4
      helm:
        releaseName: redis
        valueFiles:
          - $values/infra/values/redis.yaml
    - repoURL: https://github.com/CHoNChmonich/argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:

