apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # node-exporter: hostNetwork/hostPID/hostPath — под restricted и baseline не проходит
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: baseline
