apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: shop
spec:
  refreshInterval: 1h                       # как часто перечитывать Vault (ротация без коммита)
  secretStoreRef: { kind: ClusterSecretStore, name: vault }
  target:
    name: postgresql                            # имя Secret, которое ждёт чарт (existingSecret)
    creationPolicy: Owner
  dataFrom:
    - extract: { key: shop/postgresql }             # все ключи из secret/data/shop/postgresql -> ключи Secret как есть
