---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: shop
spec:
  encryptedData:
    password: AgA6OiCBuowm4UUB1daomnvml6uFJ2HAC1Xm9jpFA9z7f5JYmnIi7d7Tg+OKKPrUMR5fpbo2SZcocNEI/w/f9IRL/5+/TdEkFrQPcxLs7qLIwk9rWN4ESgR3+xbCXd1bjIiPdOWTkz9+m4K/9X56HkBhbZPcX4O3PDotOucPYWDynG3jCyEXuOhTmcDgND3Y7QUBmENN4oqwZA7lC3lfqYidHYfaUKVgGd8iYL1rDXYgAL5z2JR39//y2BIyxaM2uWkEH4DF0LAtHJSkVq6/qTnQ/l9vz2OMSiOi4uMKLfQ3UNfaqJMf1kLP4vSIj8+mwqbisB1H0mdZ6+Xwj2zwDO5Gaw0aOqLFMtt4+P/nwT34eqBvDzZjU9LyeBFfACtUw5mhPDFzHmmXHSaCVO61DsFRR2H2QtVgRli+GjD+lBcF4Mbn8008ntmK9v88Tg44fAB+HvnfWEokv1AkWc5mDOfot/bD1OOyfW6TNSARNGo6wbASeNknHvRUSJGT2kNFDhxQLCkToBoNdnHT03fEFf65uUfzg48Xobkt/ZNtUcTJ1Dcz15CJ45Y1TVkSx0OzuTOiHUA7TfiPflzARGbPuzIA3MXLh6Xfi0XvhZwmu7CxTi4XVIC4XdOk6N5je0+Fz/dPJxIQhOZV9t3kHizOFJHl9/Fz2sVYAHfMyhaE3cmRLSq5LKuZJM4a4rIqje65DuaBrsClKJoi1TVYvf54oJ1Qd+lClsckNbV6WP2YKTcMvA==
    postgres-password: AgAgcBfsvlQYQCCEhgvObHORDjOurwvBBJbtKRnhMEQkJgNgATCAjwFfTHoJqBhQRFvmC7buKCRATJSai9VZr9CE2JqfwVBvY0KZjronAJmE96r/3uDIPE8ooaaHItjc0YQvp6SnbvasZY2G90lw2P2C+IyNmQAemtbOpBjal+C6xkzOszJ/9Ir6OxhpiTamVzNgh0wuAMLWCz2W/HQid1S/DQwNlPTeJ/rMVVmWRKJ82+ZnaqgFcn1CndIy52chASxx3EjW1B8mHXU1OXG3cXhAV5N3ZbDWwIpp8MOG4+dlnaf5DQ8ntyEajr25SR38gdpzosYcLrWReulJL8S+H5vd9pDATWI+33IC3yrXrRUMJ0SwjWmJ0sZTMHEr+dDi0dSpagLFS4xGd6Quha+qrb1/ot49RwzY4mDdKq21pdLnIXd8a3bUGKkUA9mGjt1PEec1ZS3as355lBBG+kW1zB7lXtUXGhLo1F4/WzsvlvZ59K6/S85E+Nm+92S/yWJQ9NxC/rxmc1wt5W2j1FEAYKGxmZfseGITxzEO079EWQcS5wRNfteHdp8UgggQIeIzYr9cKbjUDt+AKU4WSUO0oHHPolt7jruFkgJuMCSjln2HuxEtlrVOAUs9HU7TCB8QH/O2QOhP+cf00uLjarmjHtyAI7624c2XpF1gn2+ISq+0Mh8Bs2wMLgrDbcTApc+Qa9mByKWS1nENpWlpIPUUjkqVRVn4e/6iMp48OJQNvuQxAA==
  template:
    metadata:
      name: postgresql
      namespace: shop
