---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq
  namespace: shop
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgBHrNk9oxw3E4/4U9qMfPazl7+4DKPBLq/hCi9dvmbJm0rNdHpZBbsa1FHu4C3BHvhT4HR7vy4xxzg//mBRnpndIqL9jhPyKx506OHlk3afJfpSKNZqAearDzEqCWhs5c9RUpmLgrErVnBn5MRNnAF/sUqDMpMocWTM6AOdon+A4xHszhITLrpP0RIMJSda03zjR6m2oj9O5Iln/6BYbxy1VDD+a2PEr6/DZYqSFXqOFNPagPW/lnI08OKtWoRSoN6/nPIBLxzLdaxJVUWnZzVDvdULp0BTfDE8wkxQuIo4gNfqIQX/bqBNodkmXs5jO5W1lNk1gEUx+nQ5lWsLxxnsoO5CuravUu5REvYik+ma5zj37yAzTv7p55kCefxcYRwTHf7RNAqBcNUr2DAQR8wgNIsDbrnZhNJ27iZ+vLqfZcRJEMUnonUQUR/tXd3fmsjF24um2y9MLqYps/aRncEesKZ8kqx6W42XfYkf1A1XeUYBPDWY9BrM7hnFQo/lw8fYuAFNpTEfY+B/PiFOn7C1WWg8Ft4kxvtVSbydehsny7URqM9ZKq/x2ZS/UwpwVHkFU9STmUxWP3QPsNG3wkV7YPLVhx+4VcyO2l+IeDV/ipGVLNJ//qbyov/wT5KGvT5btUJpwv6Jq9sEQmwmhJyNQznoc5ZwdYOkg13n8wtLu73Dc2EaOFQHJqeuZXVy2s694mPDVzej+MrZfUUvFtJU0j3erMI5TpY2IcEqCunO4A==
    rabbitmq-password: AgCepT8T/dWzAanuVwlP6IcPCncttn2FvHQr0dKIZa2snG3p3CFA7fjwaVCw5y9Y3H60TnH/93gNMYqfqUFviLCE+AuPguOLMjf8vBpbKMdYtby6NEe4TBfCV59DIPg76G7FcikWlZBzm2WTwM5qtOm9pYsLh4TEcf6W+d/Fbt6ZYNIRs5XHjtlYseb/WRiE6oSRq3FlG47vLoyb0/3ivKycxBtswY3WsbSjw378uYVjPJOHojQ1eevdoq3NiUQ4Kk+dz8xrICduyOOOs7hNodkU1hfDVAZ1PB//ig2Ms55NfE3MWTI4X7/LDiL239QNrXHWI6bqdOgDnFDUodBVtL1N8kN8c6yINO4YC8qAziEYXTYTqeREK559vXB5CqvPoDTdOuH6iapkAdCSWclfFZsCDVvTQ+/EQZ/WKhBJTp2DJ/O445W532TOca7vYEpEZvnz3N7FLbkMHkOhzoaouSIWoN1Rqzn2xpmxG49I/ieipNzGdv7aAcCQ2ebBmg05uBbZR89hrYBpio6zh76fyif90w3XnKlJVoG4A1MuCXsgwXmFdPywN1MfVz1DN+w6xWWRm/Qoq1HjHksCAdaImdt2VmdjIDR6b/OwcPcrh75o8xRjFGYeHC2L6qNJitLjSloMMrYWQ0dprYptJ3MymWyuifO2FFnQtrU/Y/cH8hs+xmhESyDJUODoJDtlujgzUoHf/FzK3eP5Y2+iVuKaqRI7hutfLG8B30H5POcIene/Pg==
  template:
    metadata:
      name: rabbitmq
      namespace: shop
