apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis
  namespace: shop
spec:
  refreshInterval: 1h                       # как часто перечитывать Vault (ротация без коммита)
  secretStoreRef: { kind: ClusterSecretStore, name: vault }
  target:
    name: redis                            # имя Secret, которое ждёт чарт (existingSecret)
    creationPolicy: Owner
  dataFrom:
    - extract: { key: shop/redis }             # все ключи из secret/data/shop/redis -> ключи Secret как есть
