---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: shop
spec:
  encryptedData:
    redis-password: AgBkp2VgHntTuPud7rzkrmm2repor6FuvDBVaPYo7E42N+rkwN3Z8iK0cRB4MEl572oNW/574N4HH83EQ/pOCfm7Z6a5RArbLlPsvH4ineNuq/FcVYmD/8/JIyrRU/ck7rfkTIEPc2D4NwNj2Ep31ZFd15FNCjUJdFzFFcg1MSTWzqI9thJmgGrq19ctv7NIuoIv/bhZiirDVuu0qBSRNQArwKu60n209xNyOXo8IrCrajOwD8rHNpS47jws0M78QiFEX+VUEo4Bo1Qlf+TC0Nfr8X02IBcJou2Bvdqtv9WSMNt424Ep1qMPWNdYpC1Mrz9lPjTIojpSWz+VFnl5LH/cWkfjCY0N4G/W/wCdwOYIlinWPPbhqJmbswYqnpu8gl/nmzo8Qmm0+9AmLKn5EpeJ6vxZVe9RmbvTeqNUXwbXpL21TSZvyUJkvbM/lReEfPE4+nz7ZOIzphTZVCZPfII272T1S+95AP9SDxoqeNpL25FmL5knlb+CWbCZqSoplS9qAkxYQympcf03UoTzC2Hvor8jnsyeyF2dvDTmx0o3Wr7ZOZ1wsTn9bZQJAHKtfcPZMLoOKlLzmS0X/FWbRensHvlio2N2Iup6W+igNpph3fgMJjlti4LUC+9sQ5G4B1JIAZPTXxR1IUyQmnCci9olpQzjZDXUKn06Bw5kAq/ONcyfuBI1cdfL/jHMQItpa7CVFUaii2AccaADiZLk+/Z+lMXk0r1BeTTeH0y9OaqKMA==
  template:
    metadata:
      name: redis
      namespace: shop
